name: TSA service CD

on:
  release:
    types: [created]

jobs:

  publish-jar:
    name: TSA service - PUBLISH JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Publish (GitHub Packages)
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    name: TSA service - PUBLISH DOCKER
    runs-on: ubuntu-latest
    env:
      REPOSITORY: bntan/tsa-service
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Compile
        run: mvn -B clean install
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build Docker image
        run: docker build -t $REPOSITORY:latest -t $REPOSITORY:${GITHUB_SHA::8} .
      - name: Push Docker image
        run: docker push $REPOSITORY