name: TSA service CI

on:
  push:
    branches: [ master ]

jobs:

  compile:
    name: TSA service - COMPILE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Compile
        run: mvn -B clean install
        
  sonar:
    name: TSA service - SONAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Run Sonar
        run: mvn -B clean install -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
